### ISSUE TITLE
How to preview fonts?

### ISSUE THREAD

**Issue by jrom99** [getnf/embellish#2]
Is there any way to preview the fonts? Either a clickable link to their homepage, or an image beside their item in the list?

I'm not sure which version I'm using since the about window and main page are not synchronised:

![image](https://github.com/user-attachments/assets/439b5307-6d74-4e01-a4a1-cf6c2eb2cf21)

**Comment by ronniedroid** [comment]
Fonts preview is planned in a future release. 

The version in the about page is Embellish's version

The version on the main page is Nerd Fonts latest version.
