### ISSUE TITLE
Flatpak doesn't work on Fedora Linux 40

### ISSUE THREAD

**Issue by skewty** [getnf/embellish#6]
Doesn't work on Fedora Linux 40 (Workstation Edition). In dark mode you can barely see the download button. Even if it is clicked, it shows no progress or error and never installs a font. Also tried using Flatseal to give it permission to All user files and that didn't fix it either.

**Comment by ronniedroid** [comment]
The dark mode install/remove button issue is correct, I just checked and I don't know how I missed that. 
But how is it not installing anything?
- Did you check if the font is being installed and usable from another app or by going to ~/.local/share/fonts?
- Does the font you click install on moving to the Installed fonts list?

**Comment by ronniedroid** [comment]
I fixed this with v0.4.3, I was not making sure that the directory at `~/Downloads/embellish` was created before downloading the tar to it. Sorry for the inconveniences.
